### ISSUE TITLE
Add support for WAL shipping replication

### ISSUE THREAD

**Issue by davidassigbi** [claranet/ansible-role-postgresql#11]
## Expected Behavior

Possibly include ssh key exchange for the postgres user
## Current Behavior

Not supported ?

## Possible Solution

```yaml
 - name: Set archive_command fact
      ansible.builtin.set_fact:
        archive_command: >-
          rsync -e ssh -az %p {{ postgresql_ip_replica if postgresql_replication_role == 'primary' else postgresql_replication_primary_address }}:/var/lib/postgresql/archived_wal/{{ postgresql_version }}/main/%f ; rsync -a %p /var/lib/postgresql/archived_wal/{{ postgresql_version }}/main/%f

postgresql_global_config_options_extra:
[...]
  - option: archive_command
    value: "{{ archive_command }}"

# Crontab pour la purge des archive wal (si réplication par wal)
    - name: Add cron job to delete files older than 3 days from /var/lib/postgresql/archived_wal
      ansible.builtin.cron:
        name: "PURGE ARCHIVED WAL"
        minute: "0"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "*"
        user: "root"
        job: "find /var/lib/postgresql/archived_wal -type f -mtime +3 -delete"
```

## Your Environment

* Version used: 1.0.0
