### ISSUE TITLE
Allow customizing how database object managment tasks connect to the postgresql instance

### ISSUE THREAD

**Issue by davidassigbi** [claranet/ansible-role-postgresql#25]
## Expected Behavior

In case a different authentication method is used for the default postgres user (other than peer, like password), there should be a simple way to have all relevant tasks use appropriate connection options.

## Current Behavior

For eg if adding a password to the postgres user, many of the engine specific tasks like user management will fail...

## Possible Solution

Add variables that holds connection options... And the user would be able to update that variable to customize connection to the instance.
```yaml
postgresql_task_convars:
  login_user: xxx
  login_password: xxx
  login_port: xxx
  login_socket: xxx
  session_role: xxx
```

## Context

This issue was raised as someone assigned a password to the postgres user in order to use a custom backup script but then many other tasks started failing.
Allowing this customization seems only fair.

## Your Environment

* Version used: v2.1.0
