### ISSUE TITLE
Add support for generating a self signed certificate for the postgresql user.

### ISSUE THREAD

**Issue by davidassigbi** [claranet/ansible-role-postgresql#6]
## Expected Behavior

Have a simple way to add ssl authentication for the postgres user using a self signed certificate

## Current Behavior

Such option is not available

## Possible Solution

génération d'un certificat autosigné (user postgres)
```bash
mkdir /var/lib/pgsql/ssl; cd /var/lib/pgsql/ssl
openssl req -new -x509 -days 365 -nodes -text -out pg-server.crt -keyout pg-server.key -subj "/CN=hostname"
chmod og-rwx pg-server.key
```

modif conf PG au niveau du host
```yaml
postgresql_global_config_options_extra:
    option : ssl
    value : on

    option : ssl_cert_file
    value : /var/lib/pgsql/ssl/pg-server.crt

    option : ssl_key_file
    value : /var/lib/pgsql/ssl/pg-server.key
```

## Context

Continual improvement

## Your Environment

* Version used: 1.0.0
